#!/bin/bash

name=`basename $0`

chmod +x chname

error_msg(){ 
	echo "$name: takes no argument bad option: $1" 1>&2 
    echo "Try '$name --help' for more information."
}

help() 
{ 
cat<<EOT 1>&2
Usage: $name
Create directories and files for the chname script and test different cases.

  -h, --help               display this help and exit

The script takes no arguments
EOT
exit 1
}

while test "x$1" != "x";do
	case "$1" in
        -h) help;;
        *) error_msg "bad option $1"; exit 1 ;;
    esac
	shift
done
echo "Creating directories..."
mkdir -p Sub{1..3}/SubS{1..3}/SubSu{1..3}/SubSub{1..2}

subdirectories=()
for x in $(find ./ -name \*); do
    if [[ -d $x ]];then
        subdirectories+=($(basename $x))
    fi
done
echo "Creating Files..."
IFS=""
for dir in ${subdirectories[*]};do
    IFS=$'\n'
    for x in $(find ./ -name $dir); do
        touch $x/File1 $x/File2 $x/'File 3'
    done
done

touch 123 FILE5 file5 File4 '1;\]{*|<,.&^%$#@!~`'

# Testing begins here
echo "File and directory creation Done!"
separator_line(){
    echo '--------------------------------------------------------------------------------------------------'
}

test_(){
    sleep 3
    separator_line
    echo $1
    echo ""
    echo $2
    echo ""
    
}

test_ 'Test chname without file/directory name and option' 'chname'
./chname

test_ 'Test chname without upper/lower option but with file/directory name' 'chname sub1'
./chname Sub1

test_ 'Test chname upper/lower option without file/directory' 'chname -u'
./chname -u 

test_ 'Test chname help(-h)' 'chname -h'
./chname -h

test_ 'Test chname help(--help)' 'chname --help'
./chname --help

test_ 'Test chname uppercase one file/directory without verbose' 'chname -u File1'
./chname -u File1

test_ 'Test chname lowercase one file/directory without verbose' 'chname -l FILE1'
./chname -l FILE1

test_ 'Test chname uppercase one file/directory with verbose' 'chname -u -v sub1'
./chname -u -v Sub1

test_ 'Test chname lowercase one file/directory with verbose' 'chname -l -v SUB1'
./chname -l -v SUB1

test_ 'Test chname uppercase multiple files/directories with verbose' 'chname -u -v sub1 sub2 File4 File2'
./chname -u -v sub1 Sub2 File4 File2 

test_ 'Test chname lowercase multiple files/directories with verbose' 'chname -l -v SUB1 SUB2 FILE4 FILE2'
./chname -l -v SUB1 SUB2 FILE4 FILE2

test_ 'Test chname uppercase/lowercase for file/directory with space with verbose' "chname -l 'File 3' "
./chname -u -v 'File 3'

test_ 'Test chname uppercase/lowercase recurssion of files with verbose' 'chname -u -r -v sub2'
./chname -u -r -v sub1

test_ 'Test chname uppercase/lowercase recurssion of subdirectories with verbose' 'chname -l -s -v sub2'
./chname -l -s -v sub2

test_ 'Test chname uppercase/lowercase recurssion of both files and subdirectories with verbose' 'chname -u -s -r -v sub3'
./chname -u -s -r -v Sub3

test_ 'Test chname lowercase/uppercase all files/directories only in the current directory starting with some letter' 'chname -u -v s*'
./chname -u -v s*

test_ 'Test chname with both upper and lowercase' 'chname -l -u -v file1 file2' 
./chname -l -u -v file1 file2 

test_ 'Test chname with non existing file/directory' 'chname -u text1'
./chname -u text1

test_ 'Test chname uppercase already uppercase files/directories' 'chname -u -v SUB1 SUB2 FILE4 FILE2'
./chname -u -v SUB1 SUB2 FILE2

test_ 'Test chname lowercase already lowercase files/directories' 'chname -l file4'
./chname -l -v file4

test_ 'Test chname if there already is another file with uppercase/lowercase' 'chname -u file5'
./chname -u file5

test_ 'Test chname on files/directories names without letter' 'chname -u 123 "1;\]{*|<,.&^%$#@!~`"'
./chname -u 123 '1;\]{*|<,.&^%$#@!~`'

test_ 'Test chname with wrong option' 'chname -u -w file5'
./chname -u -w file5
separator_line

echo 'Do you want to remove the files created'
read remove

shopt -s extglob

if test "$remove" = "y";then
    rm -r !(chname|chname_examples)
fi

